platform :ios, '9.0'
inhibit_all_warnings!         #去警告
source 'https://github.com/CocoaPods/Specs.git'

target 'rmMigrations-OC' do
    pod 'Realm'
    pod 'SDAutoLayout', '~> 2.1.3'
    pod 'MJRefresh'
end
